name: Continuous Deployment

on:
  push:
    branches:
      feature/stand_up

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.1.1

      - name: Generate Static Site
        run: ./.github/scripts/static-site-generate.sh

      - name: Zip Functions
        run: ./.github/scripts/zip-functions.sh

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve
