name: Continuous Deployment

on:
  push:
    branches:
      feature/stand_up

jobs:
  deploy:
    runs-on: ubuntu-latest

    outputs:
      apiId: ${{ steps.apply.outputs.api_id }}
      apiStage: ${{ steps.apply.outputs.api_stage }}

    steps:
      - uses: actions/checkout@v2.1.1

      - name: Generate Static Site
        run: ./.github/scripts/static-site-generate.sh

      - name: Zip Functions
        run: ./.github/scripts/zip-functions.sh

      - name: Move Files
        run: ./.github/scripts/move-files.sh

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Format
        id: fmt
        run: terraform fmt
        working-directory: infrastructure

      - name: Terraform Init
        id: init
        run: terraform init
        working-directory: infrastructure

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve
        working-directory: infrastructure

  api:
    runs-on: ubuntu-latest

    needs: deploy

    steps:
      - uses: actions/checkout@v2.1.1

      - name: Get OAS
        run: ./.github/scripts/get-oas.sh ${{needs.apply.outputs.apiId}} ${{needs.apply.outputs.apiStage}}

      - uses: readmeio/github-readme-sync@2.0.0
        with:
          readme-oas-key: '${{ secrets.README_OAS_KEY }}'
          oas-file-path: './infrastructure/oas-rendered.json'
